# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world    test !
    az login -u <username> -p <password>
    # Set the AKS context
    az aks get-credentials --resource-group rmt-rg-aks-iac --name rmt-aks-iac
    #az aks get-credentials --resource-group $aksResourceGroup --name $aksClusterName

    # Deploy Drupal and MySQL to AKS
    kubectl apply -f drupal-deployment.yaml
    kubectl apply -f mysql-deployment.yaml
  displayName: 'Build Drupal App'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
