apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_DATABASE: ZHJ1cGFsX2RhdGFic2U=
  MYSQL_USER: dXNlcg==
  MYSQL_PASSWORD: b2JzcHM=
